package com.kubsau.regrab.network

const val CONST_UNKNOWN_ERROR = 1
const val CONST_BAD_REQUEST_ERROR = 3
const val CONST_ACCESS_DENIED_ERROR = 4
const val CONST_TOKEN_FORMAT_ERROR = 5
const val CONST_UNKNOWN_TOKEN_ERROR = 6

const val CONST_WRONG_CREDENTIALS_ERROR = 101
const val CONST_WRONG_PASSWORD_ERROR = 104

const val CONST_CONTENT_NOT_FOUNT_ERROR = 1001
const val CONST_WRONG_URL_ERROR = 10001